balansNaWinstverdeling = [
    # Root
    {"Code": "", "Rubriek": "BALANS NA WINSTVERDELING", "Parent_Code": None, "Niveau": 0, "Toelichting": "", "Waarde": None},
    ## ACTIVA
    {"Code": "", "Rubriek": "ACTIVA", "Parent_Code": "", "Niveau": 1, "Toelichting": "", "Waarde": None},
    {"Code": "20", "Rubriek": "Oprichtingskosten", "Parent_Code": "ACTIVA", "Niveau": 2, "Toelichting": "6.1", "Waarde": None},
    {"Code": "21/28", "Rubriek": "Vaste activa", "Parent_Code": "ACTIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},
    {"Code": "21", "Rubriek": "Immateriële vaste activa", "Parent_Code": "21/28", "Niveau": 3, "Toelichting": "6.2", "Waarde": None},
    {"Code": "22/27", "Rubriek": "Materiële vaste activa", "Parent_Code": "21/28", "Niveau": 3, "Toelichting": "6.3", "Waarde": None},
    {"Code": "22", "Rubriek": "Terreinen en gebouwen", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "23", "Rubriek": "Installaties, machines en uitrusting", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "24", "Rubriek": "Meubilair en rollend materieel", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "25", "Rubriek": "Leasing en soortgelijke rechten", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "26", "Rubriek": "Overige materiële vaste activa", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "27", "Rubriek": "Activa in aanbouw en vooruitbetalingen", "Parent_Code": "22/27", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "28", "Rubriek": "Financiële vaste activa", "Parent_Code": "21/28", "Niveau": 3, "Toelichting": "6.4/6.5.1", "Waarde": None},
    {"Code": "280/1", "Rubriek": "Verbonden ondernemingen", "Parent_Code": "28", "Niveau": 4, "Toelichting": "6.15", "Waarde": None},
    {"Code": "280", "Rubriek": "Deelnemingen", "Parent_Code": "280/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "281", "Rubriek": "Vorderingen", "Parent_Code": "280/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "282/3", "Rubriek": "Ondernemingen met deelnemingsverhouding", "Parent_Code": "28", "Niveau": 4, "Toelichting": "6.15", "Waarde": None},
    {"Code": "282", "Rubriek": "Deelnemingen", "Parent_Code": "282/3", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "283", "Rubriek": "Vorderingen", "Parent_Code": "282/3", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "284/8", "Rubriek": "Andere financiële vaste activa", "Parent_Code": "28", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "284", "Rubriek": "Aandelen", "Parent_Code": "284/8", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "285/8", "Rubriek": "Vorderingen en borgtochten in contanten", "Parent_Code": "284/8", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "29/58", "Rubriek": "Vlottende activa", "Parent_Code": "ACTIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},
    {"Code": "29", "Rubriek": "Vorderingen op meer dan één jaar", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "290", "Rubriek": "Handelsvorderingen", "Parent_Code": "29", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "291", "Rubriek": "Overige vorderingen", "Parent_Code": "29", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "3", "Rubriek": "Voorraden en bestellingen in uitvoering", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "30/36", "Rubriek": "Voorraden", "Parent_Code": "3", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "30/31", "Rubriek": "Grond- en hulpstoffen", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "32", "Rubriek": "Goederen in bewerking", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "33", "Rubriek": "Gereed product", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "34", "Rubriek": "Handelsgoederen", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "35", "Rubriek": "Onroerende goederen bestemd voor verkoop", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "36", "Rubriek": "Vooruitbetalingen", "Parent_Code": "30/36", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "37", "Rubriek": "Bestellingen in uitvoering", "Parent_Code": "3", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "40/41", "Rubriek": "Vorderingen op ten hoogste één jaar", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "40", "Rubriek": "Handelsvorderingen", "Parent_Code": "40/41", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "41", "Rubriek": "Overige vorderingen", "Parent_Code": "40/41", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "50/53", "Rubriek": "Geldbeleggingen", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "6.5.1/6.6", "Waarde": None},
    {"Code": "50", "Rubriek": "Eigen aandelen", "Parent_Code": "50/53", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "51/53", "Rubriek": "Overige beleggingen", "Parent_Code": "50/53", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "54/58", "Rubriek": "Liquide middelen", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "490/1", "Rubriek": "Overlopende rekeningen", "Parent_Code": "29/58", "Niveau": 3, "Toelichting": "6.6", "Waarde": None},
    {"Code": "20/58", "Rubriek": "Totaal van de activa", "Parent_Code": "ACTIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},

    ## PASSIVA
    {"Code": "", "Rubriek": "PASSIVA", "Parent_Code": "", "Niveau": 1, "Toelichting": "", "Waarde": None},
    {"Code": "10/15", "Rubriek": "Eigen vermogen", "Parent_Code": "PASSIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},
    {"Code": "10/11", "Rubriek": "Inbreng", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "6.7.1", "Waarde": None},
    {"Code": "10", "Rubriek": "Kapitaal", "Parent_Code": "10/11", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "100", "Rubriek": "Geplaatst kapitaal", "Parent_Code": "10", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "101", "Rubriek": "Niet-opgevraagd kapitaal", "Parent_Code": "10", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "11", "Rubriek": "Buiten kapitaal", "Parent_Code": "10/11", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "1100/10", "Rubriek": "Uitgiftepremies", "Parent_Code": "11", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1109/19", "Rubriek": "Andere", "Parent_Code": "11", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "12", "Rubriek": "Herwaarderingsmeerwaarden", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "13", "Rubriek": "Reserves", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "130/1", "Rubriek": "Onbeschikbare reserves", "Parent_Code": "13", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "130", "Rubriek": "Wettelijke reserve", "Parent_Code": "130/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1311", "Rubriek": "Statutair onbeschikbare reserves", "Parent_Code": "130/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1312", "Rubriek": "Inkoop eigen aandelen", "Parent_Code": "130/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1313", "Rubriek": "Financiële steunverlening", "Parent_Code": "130/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1319", "Rubriek": "Overige", "Parent_Code": "130/1", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "132", "Rubriek": "Belastingvrije reserves", "Parent_Code": "13", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "133", "Rubriek": "Beschikbare reserves", "Parent_Code": "13", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "(+)/(-) 14", "Rubriek": "Overgedragen winst (verlies)", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "15", "Rubriek": "Kapitaalsubsidies", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "19", "Rubriek": "Voorschot aan vennoten op netto-actief", "Parent_Code": "10/15", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "16", "Rubriek": "Voorzieningen en uitgestelde belastingen", "Parent_Code": "PASSIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},
    {"Code": "160/5", "Rubriek": "Voorzieningen voor risico's en kosten", "Parent_Code": "16", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "160", "Rubriek": "Pensioenen en soortgelijke verplichtingen", "Parent_Code": "160/5", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "161", "Rubriek": "Belastingen", "Parent_Code": "160/5", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "162", "Rubriek": "Grote herstellings- en onderhoudswerken", "Parent_Code": "160/5", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "163", "Rubriek": "Milieuverplichtingen", "Parent_Code": "160/5", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "164/5", "Rubriek": "Overige risico's en kosten", "Parent_Code": "160/5", "Niveau": 4, "Toelichting": "6.8", "Waarde": None},
    {"Code": "168", "Rubriek": "Uitgestelde belastingen", "Parent_Code": "16", "Niveau": 3, "Toelichting": "", "Waarde": None},
    {"Code": "17/49", "Rubriek": "Schulden", "Parent_Code": "PASSIVA", "Niveau": 2, "Toelichting": "", "Waarde": None},
    {"Code": "17", "Rubriek": "Schulden op meer dan één jaar", "Parent_Code": "17/49", "Niveau": 3, "Toelichting": "6.9", "Waarde": None},
    {"Code": "170/4", "Rubriek": "Financiële schulden", "Parent_Code": "17", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "170", "Rubriek": "Achtergestelde leningen", "Parent_Code": "170/4", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "171", "Rubriek": "Niet-achtergestelde obligatieleningen", "Parent_Code": "170/4", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "172", "Rubriek": "Leasingschulden en soortgelijke schulden", "Parent_Code": "170/4", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "173", "Rubriek": "Kredietinstellingen", "Parent_Code": "170/4", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "174", "Rubriek": "Overige leningen", "Parent_Code": "170/4", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "175", "Rubriek": "Handelsschulden", "Parent_Code": "17", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "1750", "Rubriek": "Leveranciers", "Parent_Code": "175", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "1751", "Rubriek": "Te betalen wissels", "Parent_Code": "175", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "176", "Rubriek": "Vooruitbetalingen op bestellingen", "Parent_Code": "17", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "178/9", "Rubriek": "Overige schulden", "Parent_Code": "17", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "42/48", "Rubriek": "Schulden op ten hoogste één jaar", "Parent_Code": "17/49", "Niveau": 3, "Toelichting": "6.9", "Waarde": None},
    {"Code": "42", "Rubriek": "Schulden > 1 jaar binnen jaar vervallen", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "43", "Rubriek": "Financiële schulden", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "430/8", "Rubriek": "Kredietinstellingen", "Parent_Code": "43", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "439", "Rubriek": "Overige leningen", "Parent_Code": "43", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "44", "Rubriek": "Handelsschulden", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "440/4", "Rubriek": "Leveranciers", "Parent_Code": "44", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "441", "Rubriek": "Te betalen wissels", "Parent_Code": "44", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "45", "Rubriek": "Schulden m.b.t. belastingen, bezoldigingen en sociale lasten", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "6.9", "Waarde": None},
    {"Code": "450/3", "Rubriek": "Belastingen", "Parent_Code": "45", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "454/9", "Rubriek": "Bezoldigingen en sociale lasten", "Parent_Code": "45", "Niveau": 5, "Toelichting": "", "Waarde": None},
    {"Code": "46", "Rubriek": "Vooruitbetalingen op bestellingen", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "47/48", "Rubriek": "Overige schulden", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "", "Waarde": None},
    {"Code": "492/3", "Rubriek": "Overlopende rekeningen", "Parent_Code": "42/48", "Niveau": 4, "Toelichting": "6.9", "Waarde": None},
    {"Code": "10/49", "Rubriek": "Totaal van de passiva", "Parent_Code": "PASSIVA", "Niveau": 2, "Toelichting": "", "Waarde": None}
]