structuurMetadata = [
    {"Code": "Reference number", "Rubriek": "Referentienummer", "Parent_Code": "METADATA", "Niveau": 0, "Toelichting": "", "Waarde": None},
    {"Code": "Entity number", "Rubriek": "KBO-/BTW-nummer", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Accounting period start date", "Rubriek": "Boekjaar: Begin", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Accounting period end date", "Rubriek": "Boekjaar: Einde", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    # WAT DE FUCK IS DIT?????
    {"Code": "Model code", "Rubriek": "", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    # WAT DE FUCK IS DIT (2)???????
    {"Code": "Deposit type", "Rubriek": "", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Language", "Rubriek": "Taal", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Currency", "Rubriek": "Munt", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity name", "Rubriek": "Vennootschapsnaam", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity address street", "Rubriek": "Straatnaam", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity address number", "Rubriek": "Huisnummer", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity postal code", "Rubriek": "Postcode", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity city", "Rubriek": "Stad", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Entity country", "Rubriek": "Land", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "General assembly date", "Rubriek": "Datum Algemene Vergadering", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Liquidation flag", "Rubriek": "Liquidatie?", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Correction flag", "Rubriek": "Correctie?", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
    {"Code": "Legal form", "Rubriek": "Vennootschapsvorm", "Parent_Code": "METADATA", "Niveau": 0,
     "Toelichting": "", "Waarde": None},
]